prgrms-fe-devcourse/FEDC2_TTaBong_Dali

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feat.md
이슈 템플릿에 필수 사항을 적지 않아서 생긴 버그를 고쳤습니다
- about content 추가
#4
> Fix/ 이슈 템플릿 수정

- src/assets/icons/index.js
- src/components/Icon/index.jsx
- src/components/Icon/index.stories.jsx
- src/feature/BottomBar/index.jsx
```
본 PR은 기존의 #24 PR을 바탕으로 합니다.
```
👉 #24 
<br>
PR에서 리팩토링된 Icon 컴포넌트가 BottomBar만을 위해 짜여진 로직 등에 의해 
확장성이 떨어진다고 판단되었습니다.
**=> Icon 컴포넌트의 확장성을 저해하는 코드를 없애야겠다고 판단.**
<br>
PR에서 리팩토링된 BottomBar의 Icon 로직이 필요 이상으로 복잡하다고 느껴졌습니다.
**=> 기존의 복잡하던 로직을 삼항 연산자를 통해 보다 간결하게 바꿔야겠다고 판단.**
<br>
<br>
=> name이라는 직관적인 props 이름을 통해 쉽게 Icon 이미지를 변경하고자 의도.
control 옵션을 `select`로 바꿔주었습니다.
=> storybook을 props에 맞게 동작하게 하고 
앞으로도 계속 추가될 옵션 선택을 보다 쉽게 하고자 의도.
<br>
<br>
<br>
<br>
삼항 연산자를 이용하여 수정하였습니다.
=> 기존의 랜더링 로직보다 간결한 로직으로 렌더링 될 수 있도록 의도.
<br>
<br>
<br>
=> 앞으로 추가될 TTaBong들과의 분별성을 주고자 의도
<br>
<br>
<br>
혹시 더 나은 방법이 있다면 어떤 것인지 의견 부탁드립니다.
보다 자동화를 위해 storybook에 IconList 객체를 import해 
map을 통해 배열화 시켜 argTypes option에 넣는 것도 좋겠다라는 생각이 듭니다...
여러분들 의견은 어떠신지 궁금합니다.
<br>
<br>
#21
> #21/refactor/icon_2 : BottomBar 중점으로 Refactoring하기

- src/feature/BottomBar/style.jsx
- src/feature/Header/style.jsx
- src/pages/PageTemplate/index.jsx
- src/pages/PageTemplate/style.jsx
pageTemplate 컴포넌트를 구현하였습니다.
자세한 이야기는 #27 PR에서!
<br>
> #20/feat/page template 2

- src/feature/Header/style.jsx
-  feature/Header/style.jsx 오탈자 수정
> Fix/ feature/Header/style.jsx 오타 수정

- src/components/UserInfoItem/index.jsx
- src/components/UserInfoItem/index.stories.jsx
- UserInfoItem 변수명 수정 및 버그 수정
- 변수명 변경 (coin => coinCount, TTaBong => TTaBongCount)
- 코인(따봉) 갯수가 0인 경우 Title이 안나와서 default 값을 수정했습니다
close #56
> Refactor/ UserInfoItem 변수명 수정 및 버그 수정

- .storybook/main.js
- .storybook/preview.js
- package.json
- yarn.lock
yarn install하셔서 받으시면 됩니다
- Storybook viewport 추가
closed #62
> Feat/ 스토리북 뷰포트 추가

- src/feature/Header/index.jsx
- src/pages/MainFeedPage/index.jsx
MainFeedPage와 alarmIcon merge시 발생하였던 버그 수정
**yarn start에서 오류 없이 동작하는 것까지 확인 완료했습니다!!**
=> 해당 import 코드 삭제를 통해 해결
=>MainCard 디렉토리 수정을 통해 해결
=> 코드 수정을 통해 해결 (@Steadystudy 갓갓 상기님 감사합니다)
close #66
> #66/fix/main feed page

- src/components/Avatar/index.jsx
- src/components/Logo/index.jsx
필수 사항 아닌 props들 isRequired 제거
- Avatar 컴포넌트에서 avatarName, size는 필수가 아니므로 isRequired 제거하였습니다
- Logo 컴포넌트에서 type은 필수가 아니므로 isRequired 제거하였습니다
closed #74
> Refactor/ 필수 사항 아닌 props들 isRequired 제거

- src/apis/index.js
- src/components/Logo/index.jsx
- src/feature/TestApiComponent/index.jsx
- src/pages/RankPage/index.jsx
- 머지된 dev 내에 잡다한 버그 수정 (이슈 참고)
- 변경사항 수정 내용은 #96 번 이슈 참고 부탁드립니다
- 추가 수정: rankPage 내에 test channel id 상수로 전환
- 다른 버그들이 더 있으면 issue로 만들어 hot fix하면 좋을 거 같습니다
close #96
> #96/refactor/various bug fix

- src/App.jsx
- src/apis/comments.js
- src/apis/like.js
- src/apis/notifications.js
- src/components/InputForm/index.jsx
- src/components/InputForm/style.jsx
- src/feature/Cards/Card/index.jsx
- src/feature/Cards/Card/style.jsx
- src/feature/Cards/CardDetail/index.jsx
- src/feature/Cards/CardDetail/style.jsx
- src/feature/Cards/Comment/index.jsx
- src/feature/Cards/TTaBongerAndTTaBonged/index.jsx
- src/pages/CardDetailPage/index.jsx
- src/pages/CardDetailPage/index.stories.jsx
revert 로 돌린 CardDetail api 연동 작업 재 pr #79 
close #93
> Modify/ CardDetail api 재 pr

- src/contexts/UserProvider.jsx
- src/routes/AuthRoute.jsx
- src/routes/ProtectedRoute.jsx
- #112 확인 부탁드립니다
- 변수명 변경 및 버그 수정
close #112
> Refactor/ user => authUser 변수명 변경 및 로그인시 userId 받아오기

- src/feature/praise/CheckIcon/style.jsx
- src/feature/praise/TTaBongModal/index.jsx
이전 모달 pr에서 리뷰받은대로 수정했는데 push 깜빡하고 머지했습니다.
- useEffect의 async 제거
- px대신 rem
- 안쓰는 변수 제거
> Fix/ 모달창 푸시 안된 버그 픽스 커밋 재pr

- src/components/UserInfoItem/style.jsx
- src/pages/RankPage/index.jsx
- src/pages/RankPage/style.jsx
#127 이슈 해결
- UserInfoItem style 변경
close #127
> Refactor/ UI 수정

- src/assets/icons/index.js
- src/feature/pageTemplate/BottomBar/index.jsx
- src/pages/UserProfilePage/index.jsx
유저 프로필페이지 및 바텀바 버그 픽스
close #134
> #134/fix/유저 프로필 페이지, 바텀바 버그 픽스

- src/components/InputForm/index.jsx
- src/feature/cards/MainCard/index.jsx
- src/feature/praise/TTaBongModal/index.jsx
- src/pages/SearchPage/index.jsx
- src/pages/SearchPage/index.stories.jsx
- src/pages/SearchPage/style.jsx
- 버튼 누를 시 검색 submit
- 검색어 없을 경우 전체 출력
- css - > 가운데 정렬 및 카드 크기
- 카드 크기 수정
close #119
> #119/ 검색페이지 스타일 수정, 버그 픽스, 버튼 기능 추가

- src/components/BaseCardContainer/index.jsx
- src/feature/ttabong/ReasonContainer/style.jsx
- src/feature/ttabong/TTaBongModal/index.jsx
- src/pages/TTaBongPage/index.jsx
- src/pages/TTaBongPage/style.jsx
따봉페이지 세세한 부분들 업그레이드
- validation
- 따봉대상자 없는 경우
- 따봉사유 없는 경우
- 따봉 라벨 없는 경우
- 따봉 사유 너무 짧은 경우 (10글자)
- 빅따봉은 1명에게만 가능
- 빅따봉 버튼 추가 (psot.title의 type에 BigTTaBong 들어감)
close #143
> #143/ 따봉 페이지 업그레이드

- src/feature/ttabong/ImageUploadContainer/index.jsx
- src/pages/TTaBongPage/index.jsx
- Post 객체에 image api 붙였슴다
- formData를 사용해서 image를 보냈습니다
#147
> Fix/ Image post 객체에 붙이기

- src/pages/SearchPage/index.jsx
검색페이지 코인개수 구현
- 코인 카운팅 구현
close #152
> Feat/따봉페이지 코인 추가

- src/pages/MainFeedPage/index.jsx
- src/pages/MainFeedPage/style.jsx
메인피드 페이지의 limit값 변경 및 announce 추가
<br>
<br>
close #151 
<br>
> Refactor/limit값 수정 및 Announce 추가

- src/App.jsx
- src/commons/constants/error.js
- src/feature/auth/LoginForm/index.jsx
- src/feature/auth/RegisterForm/index.jsx
- src/feature/pageTemplate/Header/index.jsx
- src/feature/pageTemplate/Header/style.jsx
- src/pages/index.js
- src/routes/ProtectedRoute.jsx
- alarmPage routing 및 header routing 작업
closed #135
> Feat/ AlarmPage Protected Route 작업

- src/apis/posts.js
- post API 수정(따봉페이지 이미지 추가할 때 안넣음)
> Fix/ Post Api 수정

- src/components/Spinner/style.jsx
- src/components/Tab/style.jsx
- src/components/UserInfoItem/style.jsx
- src/feature/pageTemplate/Banner/style.jsx
- src/feature/pageTemplate/BottomBar/index.jsx
- src/feature/pageTemplate/Header/index.jsx
- src/feature/pageTemplate/Header/style.jsx
- src/feature/pageTemplate/PageTemplate/style.jsx
- src/pages/RankPage/index.jsx
- src/pages/RankPage/style.jsx
- src/pages/SearchPage/index.jsx
- src/pages/UserProfilePage/index.jsx
- src/pages/UserProfilePage/style.jsx
<br>
(윤성님은 애니메이션의 신이 아닐까...)
<br>
<br>
close #160 #165 
<br>
> #160/feat/스피너를 붙이고, 스타일을 수정하고, 약간의 로직을 뚞딲뚞딲

- src/App.jsx
- src/commons/constants/index.js
- src/components/UserInfoItem/index.jsx
- src/contexts/ChannelProvider.jsx
- src/index.jsx
- src/pages/MainFeedPage/index.jsx
- src/pages/RankPage/index.jsx
- src/pages/SearchPage/index.jsx
- src/pages/TTaBongPage/index.jsx
- src/pages/UserProfilePage/index.jsx
채널 아이디를 변수로 사용하지 말고, 채널 이름만 상수로 사용
채널 이름 상수를 통해 api로 가져온 채널 정보를 전역으로 저장
전역변수를 활용
- ChannelProvider
- Provider, global style등 전역 컴포넌트?들을 App윗단으로 옮김
- App에선 최초 channel dispatch 수행 및 받아 올 경우 라우팅 시작
- 각 페이지에서 전역 channel 변수 사용
페이지마다 잘 돌아가는지 확인해주세요
특히 app에서 channel이 제대로 들어와야 라우팅 시작하는 로직 확인 부탁드립니다.
close #169
> #169/refactor/channel Context API

- src/feature/cards/MainCard/index.jsx
- src/feature/cards/TTaBongerAndTTaBonged/index.jsx
- src/pages/CardDetailPage/index.jsx
> Fix/ 따봉드따봉러 버그수정

- src/components/UserInfoItem/index.jsx
- src/feature/rank/RankFirstInfo/index.jsx
- src/feature/ttabong/TTaBongModal/index.jsx
- src/pages/RankPage/index.jsx
- src/pages/SearchPage/index.jsx
- src/pages/TTaBongPage/index.jsx
- src/pages/UserProfilePage/index.jsx
- UserInfoItem의 props들을 user로 통합
- user로 받은 다음에 컴포넌트 안에서 구조분해할당하여 사용
- 서치페이지, 랭크페이지, 유저프로필페이지에 적용시킴
close #177
> #177/refactor/user info item props change

- src/commons/constants/error.js
- src/commons/constants/string.js
- src/pages/CardDetailPage/index.jsx
- src/pages/LoginPage/index.jsx
- src/pages/MainFeedPage/index.jsx
- src/pages/ProfileEditPage/index.jsx
- src/pages/RegisterPage/index.jsx
- src/pages/TTaBongPage/index.jsx
- src/pages/UserProfilePage/index.jsx
- 모든 alert를 toast로 교체
resolved #173
> Refactor/ alert -> Toast로 바꾸기

- src/pages/CardDetailPage/index.jsx
- src/pages/TTaBongPage/index.jsx
- src/pages/TTaBongPage/style.jsx
- 
따봉페이지에서 따봉 후 애니메이션 구현
close #185
> Feat/ 따봉 페이지 따봉 애니메이션 구현

- src/components/InputForm/index.jsx
- src/feature/cards/CardDetail/index.jsx
- src/feature/cards/CardDetail/style.jsx
- src/feature/cards/CommentList/style.jsx
- src/pages/CardDetailPage/index.jsx
> Feat/ 코멘트시 아바타 이미지 추가

- src/feature/Cards/ProfileCard/index.jsx
> Delete/ 사용하지 않는 import 삭제

- netlify.toml
- netlify.toml 설정 추가
close # 208
> Feat/ netlify 설정 추가

- src/feature/cards/ProfileCard/index.jsx
- src/feature/cards/ProfileCard/index.stories.jsx
- src/feature/cards/ProfileCard/style.jsx
- git config core.ignorecase false
close #210
> Fix/ ignorecase false
